import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const section=(start,end)=>html.split(start)[1].split(end)[0];
const ctx=vm.createContext({TextEncoder,Uint8Array,DataView,Date,Intl,structuredClone});
vm.runInContext(section('/* ROUTE_ENGINE_START:','/* ROUTE_ENGINE_END */').replace(/^.*?\*\//s,'')+'\n'+section('/* SIGHTING_LOG_START:','/* SIGHTING_LOG_END */').replace(/^.*?\*\//s,'')+'\n'+section('/* SIGHTING_EXPORT_START */','/* SIGHTING_EXPORT_END */'),ctx);
const {Log,Routes,Export,Coordinator}=vm.runInContext('({Log:SightingLog,Routes:AircraftRoutes,Export:SightingExport,Coordinator:DailyExportCoordinator})',ctx);
const T=Date.parse('2026-09-30T12:00:00Z'),DAY=86400000;
const geom={kind:'view',center:{lat:50,lon:8},bounds:{south:49.9,north:50.1,west:7.9,east:8.1}},key=Log.key(geom);
const row=(time=T,patch={})=>({hex:'3c4b31',flight:'DLH123',r:'D-AIBQ',t:'A320',lat:50,lon:8,positionTime:time,...patch});
const ingest=(log,rows,now=rows.at(-1)?.positionTime||T)=>log.record(key,'Offenburg',rows,a=>Log.inside(a,geom),now,{geometry:geom});
const route=(time=T)=>({callsign:'DLH123',source:'ADSB.lol',confidence:'likely',checkedAt:time,observationTime:time,from:{icao:'EDDF',iata:'FRA',name:'Frankfurt',lat:50.03,lon:8.57},to:{icao:'LPPT',iata:'LIS',name:'Lisbon',lat:38.77,lon:-9.13}});

test('outside/outside/inside records a second visit with a confirmed reentry',()=>{const l=new Log();for(const [i,lat] of [50,50.2,50.21,50].entries())ingest(l,[row(T+i*30000,{lat})]);const s=l.list(key,T+90000);assert.equal(s.length,1);assert.equal(s[0].visitCount,2);assert.equal(s[0].confirmedReentries,1);assert.equal(l.listVisits(key,T,T+90000).length,2);assert.equal(s[0].firstSeen,T);assert.equal(s[0].lastSeen,T+90000)});
test('one outside report and boundary jitter do not manufacture a second sighting',()=>{const l=new Log();for(const [i,lat]of [50,50.101,50.1001,50].entries())ingest(l,[row(T+i*30000,{lat})]);assert.equal(l.list(key,T+90000)[0].visitCount,1)});
test('cached duplicate, stale, future and out-of-order reports cannot add visits or advance times',()=>{const l=new Log();ingest(l,[row()]);ingest(l,[row(T-1000),row(T),row(T+1)],T);ingest(l,[row(T)],T+180000);assert.equal(l.list(key,T+180000)[0].observationCount,1);assert.equal(l.list(key,T+180000)[0].lastSeen,T)});
test('a missing signal is a session gap, not a confirmed geographic reentry',()=>{const l=new Log();ingest(l,[row()]);ingest(l,[],T+301000);ingest(l,[row(T+330000)]);const s=l.list(key,T+330000)[0];assert.equal(s.visitCount,2);assert.equal(s.confirmedReentries,0);assert.equal(l.listVisits(key,T,T+330000)[0].endReason,'signal_gap')});
test('callsign and unknown-call segments preserve one geographic visit with separate routes',()=>{const l=new Log();ingest(l,[row(T,{route:route()})]);ingest(l,[row(T+30000,{flight:'DLH456'})]);ingest(l,[row(T+60000,{flight:''})]);assert.equal(l.list(key,T+60000)[0].visitCount,1);assert.equal(l.list(key,T+60000)[0].route,null);const v=l.listVisits(key,T,T+60000);assert.equal(v.length,3);assert.equal(v[0].route.from.code,'FRA');assert.equal(v[1].route,null)});
test('rolling first seen comes from the first actual observation still in the window',()=>{const l=new Log();ingest(l,[row(T)]);ingest(l,[row(T+DAY-1000)]);ingest(l,[row(T+DAY+1000)]);const r=l.list(key,T+DAY+1500)[0];assert.equal(r.firstSeen,T+DAY-1000);assert.equal(r.visitCount,1)});
test('accepted historical routes survive ten-minute expiry and a failed live refresh',()=>{const l=new Log(),r=new Routes(),a=row();r.observe([a],T);const e=r.entry(a);r.accept(e.key,route(),T);ingest(l,[{...a,routeEpisodeKey:e.key}]);assert.equal(l.attachEntry(e,T),1);for(let i=1;i<=25;i++)ingest(l,[row(T+i*30000,{routeEpisodeKey:e.key})]);r.accept(e.key,null,T+750000);assert.equal(l.list(key,T+750000)[0].route.to.code,'LIS')});
test('a route arriving after departure enriches only its recorded episode',()=>{const l=new Log(),r=new Routes(),a=row();r.observe([a],T);const e=r.entry(a);ingest(l,[{...a,routeEpisodeKey:e.key}]);ingest(l,[row(T+30000,{lat:50.2})]);ingest(l,[row(T+60000,{lat:50.21})]);const outside=row(T+60000,{lat:50.21});r.observe([outside],T+60000);r.accept(e.key,route(T+60000),T+60000);assert.equal(l.attachEntry(e,T+60000),1);assert.equal(l.list(key,T+60000)[0].route.to.code,'LIS');ingest(l,[row(T+90000,{flight:'DLH456'})]);assert.equal(l.list(key,T+90000)[0].route,null)});
test('different flight-episode keys cannot inherit a previously accepted route',()=>{const l=new Log(),r=new Routes(),a=row();r.observe([a],T);const e=r.entry(a);r.accept(e.key,route(),T);ingest(l,[row(T,{routeEpisodeKey:'different-episode'})]);assert.equal(l.attachEntry(e,T),0)});
test('version two round trips complete visits, segments, routes and precise geometry',()=>{const l=new Log();ingest(l,[row(T,{route:route()})]);ingest(l,[row(T+30000,{flight:'DLH456'})]);const b=new Log(JSON.parse(JSON.stringify(l.export())),T+30000);assert.equal(b.listVisits(key,T,T+30000).length,2);assert.equal(b.listVisits(key,T,T+30000)[0].route.to.code,'LIS');assert.equal(b.areas.get(key).geometry.bounds.north,50.1)});
test('legacy import retains known aggregate information without inventing visit counts',()=>{const l=new Log({version:1,areas:[{key:'old',label:'Home',startedAt:T-10000,updatedAt:T,rows:[{...row(),firstSeen:T-10000,lastSeen:T,route:route()}]}]},T);const a=l.list('old',T)[0];assert.equal(a.legacy,true);assert.equal(a.visitCount,null);assert.equal(a.route.to.code,'LIS');assert.equal(l.areas.get('old').geometry,null)});
test('geometry identity includes rectangle height and preserves antimeridian membership',()=>{assert.notEqual(Log.key(geom),Log.key({...geom,bounds:{...geom.bounds,north:50.2}}));const g={kind:'view',center:{lat:0,lon:180},bounds:{south:-1,north:1,west:179,east:-179}};assert.equal(Log.inside({lat:0,lon:179.8},g),true);assert.equal(Log.inside({lat:0,lon:-179.8},g),true);assert.equal(Log.inside({lat:0,lon:0},g),false)});
test('coverage gaps are distinct from observed exits and survive serialization',()=>{const l=new Log();ingest(l,[row()]);l.markCoverageGap(key,'hidden_tab',T+1000);ingest(l,[row(T+120000)]);const a=l.areas.get(key);assert.equal(a.gaps[0].reason,'hidden_tab');assert.equal(a.gaps[0].to,T+120000);assert.equal(l.list(key,T+120000)[0].visitCount,1)});
test('pending report retention protects old evidence until report periods are frozen',()=>{const l=new Log();ingest(l,[row()]);l.keepSince=T;l.prune(T+3*DAY);assert.equal(l.listVisits(key,T,T+DAY).length,1);l.keepSince=Infinity;l.prune(T+3*DAY);assert.equal(l.listVisits(key,T,T+DAY).length,0)});
test('a visit spanning a report boundary uses the same visit ID and correct half-open periods',()=>{const l=new Log();ingest(l,[row(T+DAY-30000)]);ingest(l,[row(T+DAY)]);ingest(l,[row(T+DAY+30000)]);const first=Export.report(l,key,T,T+DAY,'Europe/Berlin',T+DAY+120000),second=Export.report(l,key,T+DAY,T+2*DAY,'Europe/Berlin',T+2*DAY);assert.equal(first.visits[0].observations,1);assert.equal(second.visits[0].observations,2);assert.equal(first.visits[0].visit_id,second.visits[0].visit_id);assert.equal(first.visits[0].carry_out,true);assert.equal(second.visits[0].carry_in,true)});
test('daily coordinator persists anchors, honors grace and creates each period only once',()=>{const l=new Log();ingest(l,[row()]);const c=new Coordinator(l);c.configure(key,true,{zone:'Europe/Berlin'},T);assert.equal(c.checkDue(T+DAY+119999).length,0);assert.equal(c.checkDue(T+DAY+120000).length,1);assert.equal(c.checkDue(T+DAY+180000).length,0);const d=new Coordinator(l);d.load(JSON.parse(JSON.stringify(c.reports)),JSON.parse(JSON.stringify(c.cycles)));assert.equal(d.checkDue(T+2*DAY+120000).length,1);assert.equal(d.reports.length,2)});
test('daylight saving changes local labels, not elapsed reporting periods',()=>{const start=Date.parse('2026-10-24T12:00:00Z'),l=new Log();ingest(l,[row(start)]);const c=new Coordinator(l);c.configure(key,true,{zone:'Europe/Berlin'},start);const r=c.checkDue(start+DAY+120000)[0];assert.equal(r.to-r.from,DAY);assert.match(Export.local(r.from,r.zone),/14:00:00/);assert.match(Export.local(r.to,r.zone),/13:00:00/)});
test('CSV handles German Excel separators, non-ASCII text, quotes and formula-like inputs',()=>{const r={visits:[{registration:'=1+1',airline:'Böhm; "Air"',callsign:'0012',first_seen_utc:'2026-09-30T12:00:00.000Z'}]};const csv=Export.csv(r);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.endsWith('\r\n'));assert.match(csv,/'=1\+1/);assert.match(csv,/Böhm; ""Air""/);assert.match(csv,/"'0012"/);assert.ok(Export.csv(r,',').includes('","'))});
test('XLSX writes a real ZIP with three OOXML sheets and string identifiers',()=>{const r={aircraft:[{icao_hex:'001234',registration:'=1+1'}],visits:[{visit_id:'x'}],recording:[{record:'period'}]};const b=Export.xlsx(r);assert.equal(new DataView(b.buffer).getUint32(0,true),0x04034b50);const text=new TextDecoder().decode(b);assert.match(text,/Aircraft/);assert.match(text,/Visits/);assert.match(text,/Recording/);assert.match(text,/t="inlineStr"/);assert.doesNotMatch(text,/<f>/)});
test('report trimming retains seven delivered reports and every pending report',()=>{const c=new Coordinator(new Log());c.reports=Array.from({length:12},(_,i)=>({id:String(i),areaKey:key,to:T+i,delivery:i<10?'download_requested':'pending'}));c.trim();assert.equal(c.reports.length,9);assert.equal(c.reports.filter(r=>r.delivery==='pending').length,2)});

test('a saved gap threshold starts a new session after the chosen interval',()=>{const l=new Log();l.record(key,'Home',[row()],a=>Log.inside(a,geom),T,{geometry:geom,gapMs:60000});l.record(key,'Home',[row(T+90000)],a=>Log.inside(a,geom),T+90000,{geometry:geom,gapMs:60000});assert.equal(l.list(key,T+90000)[0].visitCount,2);const restored=new Log(JSON.parse(JSON.stringify(l.export())),T+90000);assert.equal(restored.areas.get(key).gapMs,60000)});

test('reset clears only the chosen area, its visits and legacy rows, retaining geometry and gap settings',()=>{
 const l=new Log();ingest(l,[row()]);l.record('other','Away',[row(T,{hex:'abcdef'})],()=>true,T);const a=l.areas.get(key);a.gapMs=60000;a.legacy.set('123456',row());l.markCoverageGap(key,'hidden_tab',T+500);
 const ids=[...a.visits.keys()];assert.equal(l.reset(key,T+1000),true);assert.equal(l.list(key,T+1000).length,0);assert.equal(a.visits.size,0);assert.equal(a.tracks.size,0);assert.equal(a.legacy.size,0);assert.equal(a.gaps.length,0);assert.equal(a.openGap,null);assert.equal(a.resetAt,T+1000);assert.equal(a.gapMs,60000);assert.equal(a.geometry.bounds.north,50.1);assert.equal(l.list('other',T+1000).length,1);
 assert.ok(ids.every(id=>l.deletedVisits.has(key+'\n'+id)));assert.equal(l.reset('missing',T),false);
});
test('reset timestamp blocks cached pre-reset positions and accepts only fresh observations',()=>{
 const l=new Log();ingest(l,[row()]);l.reset(key,T+1000);ingest(l,[row(T),row(T+1000)],T+2000);assert.equal(l.list(key,T+2000).length,0);
 ingest(l,[row(T+1500)],T+2000);const a=l.list(key,T+2000)[0];assert.equal(a.firstSeen,T+1500);assert.equal(a.visitCount,1);assert.equal(a.confirmedReentries,0);
});
test('reset persists across serialization and stale tabs cannot merge deleted sightings back',()=>{
 const l=new Log();ingest(l,[row()]);const stale=JSON.parse(JSON.stringify(l.export()));l.reset(key,T+1000);const clean=JSON.parse(JSON.stringify(l.export())),restored=new Log(clean,T+2000);restored.merge(stale,T+2000);assert.equal(restored.list(key,T+2000).length,0);assert.equal(restored.areas.get(key).resetAt,T+1000);
 const oldTab=new Log(stale,T+2000);oldTab.merge(clean,T+2000);assert.equal(oldTab.list(key,T+2000).length,0);oldTab.merge(stale,T+2000);assert.equal(oldTab.list(key,T+2000).length,0);
});
test('reset restarts an enabled daily period while preserving completed reports and other cycles',()=>{
 const l=new Log();ingest(l,[row()]);l.area('other','Other',null,T);const c=new Coordinator(l);c.configure(key,true,{format:'xlsx',zone:'Europe/Berlin'},T);c.configure('other',true,{},T);const completed=c.checkDue(T+DAY+120000).map(r=>r.id);const oldOther=c.cycles.find(x=>x.key==='other').nextFrom;c.resetArea(key,T+DAY+180000);
 const active=c.cycles.find(x=>x.key===key);assert.equal(active.nextFrom,T+DAY+180000);assert.equal(active.anchor,active.nextFrom);assert.equal(active.format,'xlsx');assert.equal(active.enabled,true);assert.equal(c.cycles.find(x=>x.key==='other').nextFrom,oldOther);assert.deepEqual(c.reports.map(r=>r.id),completed);assert.equal(c.checkDue(T+2*DAY+119999).filter(r=>r.areaKey===key).length,0);
});
test('a reader reloads reset export anchors before becoming the recording owner',()=>{
 const l=new Log();ingest(l,[row()]);const owner=new Coordinator(l);owner.configure(key,true,{format:'xlsx'},T);const reader=new Coordinator(l);reader.load([],JSON.parse(JSON.stringify(owner.cycles)));
 owner.resetArea(key,T+1000);reader.load([],JSON.parse(JSON.stringify(owner.cycles)));assert.equal(reader.cycles[0].anchor,T+1000);assert.equal(reader.cycles[0].nextFrom,T+1000);assert.equal(reader.cycles[0].format,'xlsx');assert.equal(l.keepSince,T+1000);
});
test('new viewport histories reuse only recorded in-frame coordinates with original times and saved routes',()=>{
 const l=new Log(),now=T+3600000;ingest(l,[row(T,{lat:50,route:route()})]);ingest(l,[row(T+30000,{hex:'abcdef',lat:50.09})]);
 const small={...geom,bounds:{south:49.95,north:50.05,west:7.95,east:8.05}},next=Log.key(small);l.seedArea(next,'Closer view',small,now);const rows=l.list(next,now);assert.equal(rows.length,1);assert.equal(rows[0].hex,'3c4b31');assert.equal(rows[0].firstSeen,T);assert.equal(rows[0].route.to.code,'LIS');assert.equal(l.list(key,now).length,2);assert.equal(l.areas.get(next).lastSnapshotAt,0);
 l.reset(next,now+1000);l.seedArea(next,'Closer view',small,now+2000);assert.equal(l.list(next,now+2000).length,0);
});
test('viewport history reconstruction deduplicates overlapping areas and retains observed reentries',()=>{
 const l=new Log(),now=T+180000,small={...geom,bounds:{south:49.95,north:50.05,west:7.95,east:8.05}};
 for(const [i,lat]of [50,50.08,50.09,50].entries())ingest(l,[row(T+i*30000,{lat})]);
 l.record('overlap','Overlap',[row(T),row(T+90000)],()=>true,T+90000,{geometry:geom});const next=Log.key(small);l.seedArea(next,'Closer',small,now);
 const result=l.list(next,now)[0];assert.equal(result.observationCount,2);assert.equal(result.visitCount,2);assert.equal(result.confirmedReentries,1);assert.equal(result.firstSeen,T);assert.equal(result.lastSeen,T+90000);
});
test('position-free imported aggregates are not assigned fabricated coordinates to new viewports',()=>{
 const l=new Log({version:1,areas:[{key:'old',label:'Home',startedAt:T-10000,updatedAt:T,rows:[{...row(),firstSeen:T-10000,lastSeen:T}]}]},T);l.seedArea(key,'Map',geom,T+1000);assert.equal(l.list(key,T+1000).length,0);assert.equal(l.list('old',T+1000).length,1);
});
